name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: lint and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --dev --no-cache-dir

      - name: install just
        run: |
          apt install just

      - name: run linters
        run: |
          just _ci_lint

      - name: run tests
        run: |
          just _ci_test
